# Generated by Django 4.2.4 on 2024-02-24 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participator', '0002_participator_complite_participator_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='quiz_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('complite_quiz', models.ImageField(upload_to='')),
                ('participator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='participator.participator')),
            ],
        ),
    ]
