# Generated by Django 4.2.4 on 2024-02-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_history',
            name='complite_quiz',
            field=models.IntegerField(),
        ),
    ]
