# Generated by Django 4.2.4 on 2024-02-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participator',
            name='complite',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participator',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
